- name: MongoDB | Import public key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
  become: true

- name: MongoDB | Add repository
  apt_repository:
    filename: '/etc/apt/sources.list.d/mongodb-org-3.6.list'
    repo: 'deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse'
    state: present
    update_cache: yes
  become: true

- name: MongoDB | Install MongoDB
  apt:
    name: mongodb-org
    state: present
    update_cache: yes
  become: true

# - name: File to Service
#   file:
#   src: files/mongodb.service
#   dest: /etc/systemd/system/

- name: MongoDB | Ensure that MongoDB is running
  service:
    name: mongod
    state: started
    enabled: yes
  become: true
