# Add this snippet to the top of your playbook.
# It will install python2 if missing (but checks first so no expensive repeated apt updates)
# gwillem@gmail.com

- name: install python 2
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  become: true

- name: Update repositories
  apt:
    update_cache: yes
    # name: *
    # state: latest
  become: true

- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes
  become: true
